/**
 * 统一错误码（ARCHITECTURE §7 K3）。
 *
 * - `E_` 前缀 = **阻断性错误码**（鉴权 / 入参 / 未找到 / 限额 / 内部）。
 * - `W_` 前缀 = **非阻断告警码**，仅出现在 `CalorieResult.warnings`，绝不出现在 `ApiError.code`。
 */

export const ERROR_CODES = {
  // 鉴权
  AUTH_UNAUTHORIZED: 'E_AUTH_UNAUTHORIZED',
  AUTH_INVALID_TOKEN: 'E_AUTH_INVALID_TOKEN',
  AUTH_CODE_INVALID: 'E_AUTH_CODE_INVALID',
  AUTH_CODE_EXPIRED: 'E_AUTH_CODE_EXPIRED',
  AUTH_USER_DISABLED: 'E_AUTH_USER_DISABLED',

  // 入参
  VALID_INPUT: 'E_VALID_INPUT',
  VALID_CALORIE: 'E_VALID_CALORIE',
  VALID_DUPLICATE: 'E_VALID_DUPLICATE',

  // 未找到（越权访问他人资源同样返回 NOTFOUND，不泄露存在性）
  NOTFOUND_PROFILE: 'E_NOTFOUND_PROFILE',
  NOTFOUND_FOOD: 'E_NOTFOUND_FOOD',
  NOTFOUND_MEAL: 'E_NOTFOUND_MEAL',
  NOTFOUND_COMBO: 'E_NOTFOUND_COMBO',
  NOTFOUND_WEIGHT: 'E_NOTFOUND_WEIGHT',
  NOTFOUND_RESOURCE: 'E_NOTFOUND_RESOURCE',

  // 二期（T05）：运动 / 饮水 / 习惯 / 断食
  NOTFOUND_ACTIVITY: 'E_NOTFOUND_ACTIVITY',
  NOTFOUND_EXERCISE: 'E_NOTFOUND_EXERCISE',
  NOTFOUND_WATER: 'E_NOTFOUND_WATER',
  NOTFOUND_HABIT: 'E_NOTFOUND_HABIT',
  NOTFOUND_FASTING: 'E_NOTFOUND_FASTING',
  VALID_DISCLAIMER_REQUIRED: 'E_VALID_DISCLAIMER_REQUIRED',
  VALID_FASTING_DISABLED: 'E_VALID_FASTING_DISABLED',
  VALID_FASTING_RUNNING: 'E_VALID_FASTING_RUNNING',

  // 数据主权（R10）
  VALID_IMPORT_EMPTY: 'E_VALID_IMPORT_EMPTY',

  // AI（三期，R9.x）
  VALID_AI_EMPTY: 'E_VALID_AI_EMPTY',

  // 限额 / 流控
  LIMIT_THROTTLE: 'E_LIMIT_THROTTLE',
  LIMIT_AI: 'E_LIMIT_AI',

  // 内部
  INTERNAL: 'E_INTERNAL',
} as const;

/** 错误码取值联合类型。 */
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
