-- =============================================================================
-- 「轻生活」数据库 DDL —— PostgreSQL 16 方言（生产环境）【人工参照文档，可能滞后】
--
-- ⚠️ 唯一真源（single source of truth）= apps/api/prisma/schema.pg.prisma。
--    生产/CI 实际建表走：`prisma db push --schema apps/api/prisma/schema.pg.prisma`
--    （见 render.yaml）。本文件**仅人工阅读/参考**，不参与建表，内容**可能滞后于真源**，
--    请勿据此 DDL 建库；如需以真源为准，直接看 prisma/schema.pg.prisma。
--
-- 执行（可选）： psql "$DATABASE_URL" -f docs/schema.pg.sql
-- 与 docs/SCHEMA.sql（SQLite，MVP）表/约束一一对应，差异见 docs/ARCHITECTURE.md §3.2
-- 差异映射： INTEGER->BIGINT IDENTITY | INTEGER(0/1)->BOOLEAN | TEXT(日期)->DATE
--            TEXT(时间戳)->TIMESTAMPTZ | strftime->now()
-- 「JSON 语义」列一律 TEXT（存 JSON 文本，由应用层 JSON.parse/stringify）——
--   dietary_preference / conditions / macro_ratio / aliases / serving_units /
--   ai_traces.steps / ai_traces.pending_tool。（历史上曾写作 JSONB，已按代码契约改为 TEXT。）
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. users
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email              TEXT        NOT NULL,
  password_hash      TEXT,
  email_verified_at  TIMESTAMPTZ,
  status             TEXT        NOT NULL DEFAULT 'active' CHECK (status IN ('active','disabled')),
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email ON users(email);

-- -----------------------------------------------------------------------------
-- 2. auth_verification_codes
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS auth_verification_codes (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email        TEXT        NOT NULL,
  code_hash    TEXT        NOT NULL,
  purpose      TEXT        NOT NULL DEFAULT 'login' CHECK (purpose IN ('login','signup','reset')),
  expires_at   TIMESTAMPTZ NOT NULL,
  consumed_at  TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_avc_email_purpose ON auth_verification_codes(email, purpose, expires_at);

-- -----------------------------------------------------------------------------
-- 3. user_profiles
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_profiles (
  user_id                BIGINT      PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  gender                 TEXT        NOT NULL CHECK (gender IN ('male','female')),
  birth_date             DATE        NOT NULL,
  height_cm              DOUBLE PRECISION NOT NULL CHECK (height_cm > 0),
  activity_level         TEXT        NOT NULL CHECK (activity_level IN ('sedentary','light','moderate','high','athlete')),
  dietary_preference     TEXT        NOT NULL DEFAULT '[]',   -- JSON 文本（应用层 JSON.parse）
  conditions             TEXT        NOT NULL DEFAULT '[]',   -- JSON 文本；敏感字段（D3）
  disclaimer_accepted_at TIMESTAMPTZ,
  onboarding_completed_at TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 4. user_goals
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_goals (
  user_id          BIGINT      PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  start_weight_kg  DOUBLE PRECISION NOT NULL,
  target_weight_kg DOUBLE PRECISION NOT NULL CHECK (target_weight_kg > 0),
  target_weeks     INTEGER     NOT NULL CHECK (target_weeks > 0),
  weekly_loss_kg   DOUBLE PRECISION NOT NULL CHECK (weekly_loss_kg > 0),
  macro_ratio      TEXT        NOT NULL DEFAULT '{"protein":25,"fat":25,"carb":50}',  -- JSON 文本
  is_active        BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 5. weight_goal_history
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS weight_goal_history (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  start_weight_kg  DOUBLE PRECISION NOT NULL,
  target_weight_kg DOUBLE PRECISION NOT NULL,
  target_weeks     INTEGER     NOT NULL,
  weekly_loss_kg   DOUBLE PRECISION NOT NULL,
  macro_ratio      TEXT        NOT NULL DEFAULT '{"protein":25,"fat":25,"carb":50}',  -- JSON 文本
  effective_from   DATE        NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_wgh_user_from ON weight_goal_history(user_id, effective_from);

-- -----------------------------------------------------------------------------
-- 6. user_settings
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_settings (
  user_id         BIGINT      PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  unit            TEXT        NOT NULL DEFAULT 'kcal' CHECK (unit IN ('kcal','kj')),
  dark_mode       BOOLEAN     NOT NULL DEFAULT FALSE,
  water_goal_ml   INTEGER     NOT NULL DEFAULT 2000 CHECK (water_goal_ml > 0),
  fasting_enabled BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 7. weight_logs
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS weight_logs (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  logged_at  DATE        NOT NULL,
  weight_kg  DOUBLE PRECISION NOT NULL CHECK (weight_kg > 0 AND weight_kg < 500),
  note       TEXT,
  source     TEXT        NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','import')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_weight_user_day ON weight_logs(user_id, logged_at);
CREATE INDEX IF NOT EXISTS ix_weight_user_at ON weight_logs(user_id, logged_at);

-- -----------------------------------------------------------------------------
-- 8. food_items
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS food_items (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                     TEXT    NOT NULL,
  name_pinyin              TEXT,
  aliases                  TEXT    NOT NULL DEFAULT '[]',  -- JSON 文本（应用层 JSON.parse）
  category                 TEXT    NOT NULL DEFAULT 'other',
  kcal_per_100g            DOUBLE PRECISION NOT NULL CHECK (kcal_per_100g >= 0),
  protein_g_per_100g       DOUBLE PRECISION NOT NULL DEFAULT 0,
  fat_g_per_100g           DOUBLE PRECISION NOT NULL DEFAULT 0,
  carb_g_per_100g          DOUBLE PRECISION NOT NULL DEFAULT 0,
  fiber_g_per_100g         DOUBLE PRECISION,
  sodium_mg_per_100g       DOUBLE PRECISION,
  saturated_fat_g_per_100g DOUBLE PRECISION,
  sugar_g_per_100g         DOUBLE PRECISION,
  calcium_mg_per_100g      DOUBLE PRECISION,
  iron_mg_per_100g         DOUBLE PRECISION,
  potassium_mg_per_100g    DOUBLE PRECISION,
  vitamin_d_ug_per_100g    DOUBLE PRECISION,
  b12_ug_per_100g          DOUBLE PRECISION,
  magnesium_mg_per_100g    DOUBLE PRECISION,
  serving_units            TEXT    NOT NULL DEFAULT '[]',  -- JSON 文本（应用层 JSON.parse）
  default_serving_grams    DOUBLE PRECISION,
  barcode                  TEXT,
  source                   TEXT    NOT NULL DEFAULT 'builtin' CHECK (source IN ('builtin','openfoodfacts','user_custom')),
  created_by_user_id       BIGINT  REFERENCES users(id) ON DELETE CASCADE,
  is_verified              BOOLEAN NOT NULL DEFAULT FALSE,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_food_name     ON food_items(name);
CREATE INDEX IF NOT EXISTS ix_food_pinyin   ON food_items(name_pinyin);
CREATE INDEX IF NOT EXISTS ix_food_category ON food_items(category);
CREATE INDEX IF NOT EXISTS ix_food_source   ON food_items(source);
CREATE UNIQUE INDEX IF NOT EXISTS ux_food_barcode ON food_items(barcode) WHERE barcode IS NOT NULL;
-- 模糊搜索加速（可选，二期）：CREATE EXTENSION IF NOT EXISTS pg_trgm;
-- CREATE INDEX IF NOT EXISTS ix_food_name_trgm ON food_items USING gin (name gin_trgm_ops);

-- -----------------------------------------------------------------------------
-- 9. food_favorites
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS food_favorites (
  user_id      BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  food_item_id BIGINT      NOT NULL REFERENCES food_items(id) ON DELETE CASCADE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, food_item_id)
);

-- -----------------------------------------------------------------------------
-- 10. meal_logs
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS meal_logs (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  logged_date  DATE        NOT NULL,
  meal_type    TEXT        NOT NULL CHECK (meal_type IN ('breakfast','lunch','dinner','snack')),
  food_item_id BIGINT      REFERENCES food_items(id) ON DELETE SET NULL,
  custom_name  TEXT,
  grams        DOUBLE PRECISION,
  serving_unit TEXT,
  serving_qty  DOUBLE PRECISION,
  kcal         DOUBLE PRECISION NOT NULL CHECK (kcal >= 0),
  protein_g    DOUBLE PRECISION,
  fat_g        DOUBLE PRECISION,
  carb_g       DOUBLE PRECISION,
  fiber_g      DOUBLE PRECISION,
  sodium_mg    DOUBLE PRECISION,
  source       TEXT        NOT NULL DEFAULT 'search'
               CHECK (source IN ('search','quick_add','barcode','ai','combo')),
  combo_id     BIGINT,     -- 后置外键：meal_combos 在本表之后创建
  note         TEXT,
  sort_order   INTEGER     NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_meal_user_date      ON meal_logs(user_id, logged_date);
CREATE INDEX IF NOT EXISTS ix_meal_user_date_type ON meal_logs(user_id, logged_date, meal_type);
CREATE INDEX IF NOT EXISTS ix_meal_user_food      ON meal_logs(user_id, food_item_id);

-- -----------------------------------------------------------------------------
-- 11. meal_combos
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS meal_combos (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name       TEXT        NOT NULL,
  meal_type  TEXT        NOT NULL DEFAULT 'breakfast' CHECK (meal_type IN ('breakfast','lunch','dinner','snack')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_combo_user_name ON meal_combos(user_id, name);

-- 补上 meal_logs.combo_id 外键（延迟创建以解决循环引用）
ALTER TABLE meal_logs
  DROP CONSTRAINT IF EXISTS fk_meal_combo;
ALTER TABLE meal_logs
  ADD CONSTRAINT fk_meal_combo FOREIGN KEY (combo_id) REFERENCES meal_combos(id) ON DELETE SET NULL;

-- -----------------------------------------------------------------------------
-- 12. meal_combo_items
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS meal_combo_items (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  combo_id     BIGINT      NOT NULL REFERENCES meal_combos(id) ON DELETE CASCADE,
  food_item_id BIGINT      REFERENCES food_items(id) ON DELETE SET NULL,
  custom_name  TEXT,
  grams        DOUBLE PRECISION,
  serving_unit TEXT,
  serving_qty  DOUBLE PRECISION,
  kcal         DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (kcal >= 0),
  protein_g    DOUBLE PRECISION,
  fat_g        DOUBLE PRECISION,
  carb_g       DOUBLE PRECISION,
  sort_order   INTEGER     NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS ix_combo_item_combo ON meal_combo_items(combo_id);

-- -----------------------------------------------------------------------------
-- 13. met_activities
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS met_activities (
  code       TEXT        PRIMARY KEY,
  name       TEXT        NOT NULL,
  category   TEXT        NOT NULL DEFAULT 'other',
  intensity  TEXT,
  met        DOUBLE PRECISION NOT NULL CHECK (met > 0),
  is_builtin BOOLEAN     NOT NULL DEFAULT TRUE,
  source     TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 14. exercise_logs
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS exercise_logs (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  logged_date      DATE        NOT NULL,
  activity_code    TEXT        NOT NULL REFERENCES met_activities(code) ON DELETE RESTRICT,
  activity_name    TEXT        NOT NULL,
  met              DOUBLE PRECISION NOT NULL CHECK (met > 0),
  minutes          DOUBLE PRECISION NOT NULL CHECK (minutes > 0),
  weight_kg_at_log DOUBLE PRECISION NOT NULL CHECK (weight_kg_at_log > 0),
  kcal_burned      DOUBLE PRECISION NOT NULL CHECK (kcal_burned >= 0),
  note             TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_exercise_user_date ON exercise_logs(user_id, logged_date);

-- -----------------------------------------------------------------------------
-- 15. water_logs
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS water_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  logged_date DATE        NOT NULL,
  logged_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  amount_ml   INTEGER     NOT NULL CHECK (amount_ml > 0),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_water_user_date ON water_logs(user_id, logged_date, logged_at);

-- -----------------------------------------------------------------------------
-- 16. habit_definitions
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS habit_definitions (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT      REFERENCES users(id) ON DELETE CASCADE,
  code           TEXT        NOT NULL,
  name           TEXT        NOT NULL,
  icon           TEXT,
  target_per_day INTEGER     NOT NULL DEFAULT 1 CHECK (target_per_day > 0),
  is_active      BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- NULLS NOT DISTINCT (PG15+) 使 (NULL,code) 也唯一，保证内置习惯不重复
CREATE UNIQUE INDEX IF NOT EXISTS ux_habit_user_code ON habit_definitions(user_id, code) NULLS NOT DISTINCT;

-- -----------------------------------------------------------------------------
-- 17. habit_checkins
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS habit_checkins (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  habit_id    BIGINT      NOT NULL REFERENCES habit_definitions(id) ON DELETE CASCADE,
  logged_date DATE        NOT NULL,
  done        BOOLEAN     NOT NULL DEFAULT TRUE,
  value       DOUBLE PRECISION,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_checkin_user_habit_day ON habit_checkins(user_id, habit_id, logged_date);

-- -----------------------------------------------------------------------------
-- 18. fasting_settings
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fasting_settings (
  user_id           BIGINT      PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  plan              TEXT        NOT NULL DEFAULT '16:8' CHECK (plan IN ('16:8','18:6','custom')),
  target_fast_hours DOUBLE PRECISION NOT NULL DEFAULT 16 CHECK (target_fast_hours > 0),
  eat_window_start  TEXT,
  enabled           BOOLEAN     NOT NULL DEFAULT FALSE,
  disclaimer_ack_at TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 19. fasting_sessions
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fasting_sessions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  plan         TEXT        NOT NULL DEFAULT '16:8',
  target_hours DOUBLE PRECISION NOT NULL DEFAULT 16,
  started_at   TIMESTAMPTZ NOT NULL,
  ended_at     TIMESTAMPTZ,
  completed    BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_fasting_user_started ON fasting_sessions(user_id, started_at);

-- -----------------------------------------------------------------------------
-- 20. ai_usage
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_usage (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  usage_date    DATE        NOT NULL,
  feature       TEXT        NOT NULL CHECK (feature IN ('daily_summary','today_plan','free_ask','food_recognize')),
  request_count INTEGER     NOT NULL DEFAULT 0 CHECK (request_count >= 0),
  token_in      INTEGER     NOT NULL DEFAULT 0,
  token_out     INTEGER     NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_ai_usage_user_day_feature ON ai_usage(user_id, usage_date, feature);

-- -----------------------------------------------------------------------------
-- 21. ai_traces —— Agent 执行轨迹（可观测性：工具调用链 / 耗时 / token / 结果）
--     steps / pending_tool 为 JSON 文本（TEXT），由应用层 JSON.parse/stringify；
--     pending_tool 仅在待用户确认时非空，确认/抢占后置 NULL。
--     本表无 updated_at（追加式轨迹，不更新），故不参与下方 updated_at 触发器集合。
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_traces (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  question     TEXT        NOT NULL,
  status       TEXT        NOT NULL
               CHECK (status IN ('answered','need_confirm','max_steps','failed','disabled')),
  answer       TEXT,
  steps        TEXT        NOT NULL,        -- JSON 文本：AgentStep[]
  pending_tool TEXT,                        -- JSON 文本：{ name, args }；无待确认时为 NULL
  tool_calls   INTEGER     NOT NULL DEFAULT 0,
  tokens       INTEGER     NOT NULL DEFAULT 0,
  duration_ms  INTEGER     NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_ai_traces_user_id ON ai_traces(user_id, id);

-- =============================================================================
-- updated_at 自动维护（PG 原生支持触发器函数）
-- =============================================================================
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'users','user_profiles','user_goals','user_settings','weight_logs',
    'food_items','meal_logs','meal_combos','exercise_logs',
    'habit_definitions','fasting_settings','fasting_sessions','ai_usage'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%s_touch ON %I;', t, t);
    EXECUTE format('CREATE TRIGGER trg_%s_touch BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at();', t, t);
  END LOOP;
END $$;
